### ISSUE TITLE
aiohttp exception when Shelly device is password protected

### ISSUE THREAD

**Issue by bieniu** [home-assistant-libs/aioshelly#1]
When Shelly device is password protected I get this error:
```text
Traceback (most recent call last):
  File "shelly.py", line 24, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "shelly.py", line 8, in main
    device = await aioshelly.Device.create("192.168.2.185", session)
  File "/home/maciek/.virtualenvs/hass/lib/python3.8/site-packages/aioshelly/__init__.py", line 31, in create
    await instance.initialize()
  File "/home/maciek/.virtualenvs/hass/lib/python3.8/site-packages/aioshelly/__init__.py", line 62, in initialize
    self.settings = await self.http_request("get", "settings")
  File "/home/maciek/.virtualenvs/hass/lib/python3.8/site-packages/aioshelly/__init__.py", line 76, in http_request
    return await resp.json()
  File "/home/maciek/.virtualenvs/hass/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain', url=URL('http://192.168.2.185/settings')
Exception ignored in: <function RecvmsgSelectorDatagramTransport.__del__ at 0x7fb7c86af3a0>
Traceback (most recent call last):
  File "/home/maciek/.virtualenvs/hass/lib/python3.8/site-packages/aiocoap/util/asyncio/recvmsg.py", line 72, in __del__
  File "/home/maciek/.virtualenvs/hass/lib/python3.8/site-packages/aiocoap/util/asyncio/recvmsg.py", line 60, in close
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by balloob** [comment]
Auth is not supported yet. PRs welcome 👍
