### ISSUE TITLE
Multiple IPs/Networks on the same network interface are broken

### ISSUE THREAD

**Issue by gesslein** [home-assistant-libs/aioshelly#68]
This is a follow up to my comment in home-assistant/core/issues/45957
With latest core-2021.2.0 I get the following error in homeassistant log:
```
2021-02-04 21:53:21 DEBUG (MainThread) [aioshelly.coap] Adding ip 127.0.0.1 to multicast 224.0.1.187 membership
2021-02-04 21:53:21 DEBUG (MainThread) [aioshelly.coap] Adding ip 127.0.0.1 to multicast 224.0.1.188 membership
2021-02-04 21:53:21 DEBUG (MainThread) [aioshelly.coap] Adding ip 192.168.2.10 to multicast 224.0.1.187 membership
2021-02-04 21:53:21 DEBUG (MainThread) [aioshelly.coap] Adding ip 192.168.2.10 to multicast 224.0.1.188 membership
2021-02-04 21:53:21 DEBUG (MainThread) [aioshelly.coap] Adding ip 192.168.11.11 to multicast 224.0.1.187 membership
2021-02-04 21:53:21 DEBUG (MainThread) [aioshelly.coap] Adding ip 192.168.11.11 to multicast 224.0.1.188 membership
2021-02-04 21:53:21 DEBUG (MainThread) [aioshelly.coap] Adding ip 172.17.0.1 to multicast 224.0.1.187 membership
2021-02-04 21:53:21 DEBUG (MainThread) [aioshelly.coap] Adding ip 172.17.0.1 to multicast 224.0.1.188 membership
2021-02-04 21:53:21 DEBUG (MainThread) [aioshelly.coap] Adding ip 172.30.32.1 to multicast 224.0.1.187 membership
2021-02-04 21:53:21 DEBUG (MainThread) [aioshelly.coap] Adding ip 172.30.32.1 to multicast 224.0.1.188 membership
2021-02-04 21:53:21 DEBUG (MainThread) [aioshelly.coap] Adding ip 192.168.2.5 to multicast 224.0.1.187 membership
2021-02-04 21:53:21 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Arbeitszimmer Rollladen for shelly
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/shelly/__init__.py", line 84, in async_setup_entry
    coap_context = await get_coap_context(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/singleton.py", line 42, in async_wrapped
    result = await func(hass)
  File "/usr/src/homeassistant/homeassistant/components/shelly/__init__.py", line 54, in get_coap_context
    await context.initialize()
  File "/usr/local/lib/python3.8/site-packages/aioshelly/coap.py", line 86, in initialize
    self.sock = socket_init()
  File "/usr/local/lib/python3.8/site-packages/aioshelly/coap.py", line 66, in socket_init
    sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, group)
OSError: [Errno 98] Address in use
```

This is how my network interface is configured:
```
root@kodlixio:~# ip a s enp1s0
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:e0:4c:3b:d5:b5 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.10/24 brd 192.168.2.255 scope global dynamic enp1s0
       valid_lft 84408sec preferred_lft 84408sec
    inet 192.168.2.5/32 brd 192.168.2.5 scope global enp1s0:0
       valid_lft forever preferred_lft forever
```
Multicast groups need to be joined once for each "real" network interface, not once for each IP on that interface. Removing the secondary ip from the interface allows the integration to start without error.

**Comment by chemelli74** [comment]
Hi, can you please show me `ifconfig `output ?

Simone

**Comment by gesslein** [comment]
```
enp1s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.2.10  netmask 255.255.255.0  broadcast 192.168.2.255
        ether 00:e0:4c:3b:d5:b5  txqueuelen 1000  (Ethernet)
        RX packets 999865  bytes 863513330 (823.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 582067  bytes 180585649 (172.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp1s0:0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.2.5  netmask 255.255.255.255  broadcast 192.168.2.5
        ether 00:e0:4c:3b:d5:b5  txqueuelen 1000  (Ethernet)
```

Going by the MAC might be possible?

To reproduce such a setup, this is how its configured in /etc/network/interfaces and then `ifup enp1s0:0`
```
allow-hotplug enp1s0
iface enp1s0 inet dhcp

auto enp1s0:0
iface enp1s0:0 inet static
address 192.168.2.5
netmask 255.255.255.255
```

**Comment by chemelli74** [comment]
>inet 192.168.2.5  netmask 255.255.255.255  broadcast 192.168.2.5

and

> netmask 255.255.255.255

Why ?

Simone

**Comment by gesslein** [comment]
The problem is the same with 255.255.255.0 (or any other netmask i guess), and also a completely different network range.

**Comment by psvanstrom** [comment]
I get the same issue `OSError: [Errno 98] Address in use`. I'm running HA in a docker instance from this repo: https://registry.hub.docker.com/r/homeassistant/home-assistant/

```
bond0     Link encap:Ethernet  HWaddr A0:8C:FD:C3:FE:FA  
          UP BROADCAST RUNNING PROMISC MASTER MULTICAST  MTU:1500  Metric:1
          RX packets:153559652 errors:0 dropped:153 overruns:0 frame:0
          TX packets:76375766 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:211188064898 (196.6 GiB)  TX bytes:6471353955 (6.0 GiB)

br0       Link encap:Ethernet  HWaddr A0:8C:FD:C3:FE:FA  
          inet addr:192.168.40.10  Bcast:192.168.40.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:210614657 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5068714 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:210966096256 (196.4 GiB)  TX bytes:1544757369 (1.4 GiB)

docker0   Link encap:Ethernet  HWaddr 02:42:BB:3E:DD:F3  
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          inet6 addr: fe80::42:bbff:fe3e:ddf3/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3813573 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4499666 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:827380645 (789.0 MiB)  TX bytes:1581203225 (1.4 GiB)

eth0      Link encap:Ethernet  HWaddr A0:8C:FD:C3:FE:FA  
          UP BROADCAST RUNNING SLAVE MULTICAST  MTU:1500  Metric:1
          RX packets:153559652 errors:0 dropped:153 overruns:0 frame:0
          TX packets:76375766 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:211188064898 (196.6 GiB)  TX bytes:6471353955 (6.0 GiB)
          Interrupt:16 Memory:d1100000-d1120000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:82893 errors:0 dropped:0 overruns:0 frame:0
          TX packets:82893 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:7958065 (7.5 MiB)  TX bytes:7958065 (7.5 MiB)

shim-br0  Link encap:Ethernet  HWaddr AE:4C:96:DC:ED:0A  
          inet addr:192.168.40.10  Bcast:0.0.0.0  Mask:255.255.255.255
          inet6 addr: fe80::ac4c:96ff:fedc:ed0a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4456614 errors:0 dropped:0 overruns:0 frame:0
          TX packets:236000 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:16203707292 (15.0 GiB)  TX bytes:21834022 (20.8 MiB)
```

**Comment by pp-svanstrom** [comment]
Works with 2021.2.1 👍

**Comment by nzapponi** [comment]
I don't think it does. It's just that in 2021.2.1 they reverted aioshelly back to v0.5.1.

**Comment by nzapponi** [comment]
See https://github.com/home-assistant/core/issues/45957

**Comment by chemelli74** [comment]
HA is currently supporting only 1 network interface, this is why we reverted multiple interface binding.

Simone
